/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_MODEL_VARIABLES_H_
#define _EI_CLASSIFIER_MODEL_VARIABLES_H_

/**
 * @file
 *  Auto-generated complete impulse definitions. The ei_impulse_handle_t should
 *  be passed to ei_run_classifier() function to use this specific impulse.
 *  This file should only be included in ei_run_classifier.h file.
 */

#include <stdint.h>
#include <vector>
#include "model_metadata.h"
#include "tflite-model/tflite_learn_1128090_3_compiled.h"
#include "edge-impulse-sdk/classifier/ei_model_types.h"
#include "edge-impulse-sdk/classifier/inferencing_engines/engines.h"
#include "edge-impulse-sdk/classifier/postprocessing/ei_postprocessing_common.h"

const char* ei_classifier_inferencing_categories_1128090_1[] = { "Bad_contact", "Cloud", "Normal", "Overheat" };

EI_CLASSIFIER_DSP_AXES_INDEX_TYPE ei_dsp_config_1128090_2_axes[] = { 0, 1, 2, 3, 4, 5 };
const uint32_t ei_dsp_config_1128090_2_axes_size = 6;
ei_dsp_config_flatten_t ei_dsp_config_1128090_2 = {
    2, // uint32_t blockId
    1, // int implementationVersion
    6, // int length of axes
    1.0f, // float scale-axes
    true, // boolean average
    true, // boolean minimum
    true, // boolean maximum
    true, // boolean rms
    true, // boolean stdev
    true, // boolean skewness
    true, // boolean kurtosis
    0 // int moving_avg_num_windows
};

const float ei_dn_standard_scaler_mean_1128090_2[42] = { 673.7823831467401, 673.2439880371094, 674.3050003051758, 673.7824932280041, 0.3189919560293977, -0.029530109400054374, -1.02026026694858, 7.899685740470886, 7.537500028099332, 8.242261883758363, 7.917475784108753, 0.21386369790083595, -0.0705999127752702, -0.8585590455317981, 5323.614823114304, 5078.041013445173, 5555.829344249907, 5335.728954496838, 144.88630420821053, -0.07703882131248802, -0.8697591256433432, 52.03751548131307, 51.40589293979463, 52.65416669845581, 52.040334678831556, 0.3666243835191597, -0.06953817001444154, -0.9703490021028778, 27.53863061042059, 27.514880838848295, 27.562738066627865, 27.538635117667063, 0.014302464725915343, -0.029680800158876947, -0.9242996327091186, 800.0369088309152, 764.4869059608096, 833.6809527079264, 801.8134242466518, 20.831651002479095, -0.06737326797273065, -0.9054290036465751 };
const float ei_dn_standard_scaler_scale_1128090_2[42] = { 0.3442710429399909, 0.34649024821856145, 0.3424213514243559, 0.34427062558488736, 4.492525364539605, 2.7323075468242033, 2.1672027192951537, 0.7102460147095411, 0.5542562818015582, 0.9409242640128895, 0.7252434824970485, 2.543999386690754, 1.7678258231108581, 1.5654590149139314, 0.0010502025108553724, 0.0008205963068345628, 0.0013853153714009213, 0.001072359699655551, 0.0037514360622311984, 1.7486513635453484, 1.545771542439276, 0.0838952738455393, 0.08650205748808794, 0.0815049537383722, 0.08388275798508174, 2.2280289239959195, 2.0803518624147013, 2.3494163139894275, 1.0592900594481385, 1.0546354323682492, 1.0646407266901083, 1.0592915703984345, 136.78807336945937, 2.2852005553313326, 0.9322268920972256, 0.006942432835393289, 0.005400262678572157, 0.00929475338935076, 0.007088677262612956, 0.02528206397130418, 1.8451923403458674, 1.8129363577998503 };
const float ei_dn_standard_scaler_var_1128090_2[42] = { 8.43721293124236, 8.329481495766057, 8.528611391081498, 8.437233387916551, 0.049547178056149485, 0.13394941975101413, 0.21291238560611297, 1.982359374802142, 3.2552080587123644, 1.1295115181350175, 1.9012198094762685, 0.15451334533616082, 0.31997868779568445, 0.40805301981045516, 906679.7066687454, 1485049.3426891416, 521077.9473399813, 869598.9990852295, 71056.67839081043, 0.327034475865908, 0.4185134161580993, 142.07740231195191, 133.6432797244618, 150.53309450120778, 142.11980324500107, 0.201445862117182, 0.23106087199189712, 0.1811673950541062, 0.8911897983216323, 0.8990736792761919, 0.8822544320765499, 0.8911872559762256, 0.00005344456353818478, 0.19149231882112158, 1.1506857798406847, 20748.01848675315, 34290.216691983886, 11575.08681796164, 19900.756783265097, 1564.4977691723939, 0.2937086342137438, 0.3042530094459676 };
ei_data_normalization_standard_scaler_config_t ei_data_normalization_standard_scaler_config_1128090_2 = {
    .mean_data = (float *)ei_dn_standard_scaler_mean_1128090_2,
    .mean_data_len = 42,
    .scale_data = (float *)ei_dn_standard_scaler_scale_1128090_2,
    .scale_data_len = 42,
    .var_data = (float *)ei_dn_standard_scaler_var_1128090_2,
    .var_data_len = 42
};
ei_data_normalization_t ei_data_normalization_config_1128090_2 = {
    (void *) &ei_data_normalization_standard_scaler_config_1128090_2, // config
    DATA_NORMALIZATION_METHOD_STANDARD_SCALER, // method
    nullptr, // context
    nullptr, // init func
    nullptr, // deinit func
    &data_normalization_standard_scaler // exec func
};

const uint8_t ei_dsp_blocks_1128090_1_size = 1;
ei_model_dsp_t ei_dsp_blocks_1128090_1[ei_dsp_blocks_1128090_1_size] = {
    { // DSP block 2
        2,
        42, // output size
        &extract_flatten_features, // DSP function pointer
        (void*)&ei_dsp_config_1128090_2, // pointer to config struct
        ei_dsp_config_1128090_2_axes, // array of offsets into the input stream, one for each axis
        ei_dsp_config_1128090_2_axes_size, // number of axes
        1, // version
        flatten_class::create, // factory function
        &ei_data_normalization_config_1128090_2, // data normalization config
    }
};
const ei_config_tflite_eon_graph_t ei_config_graph_1128090_3 = {
    .implementation_version = 1,
    .model_init = &tflite_learn_1128090_3_init,
    .model_invoke = &tflite_learn_1128090_3_invoke,
    .model_reset = &tflite_learn_1128090_3_reset,
    .model_input = &tflite_learn_1128090_3_input,
    .model_output = &tflite_learn_1128090_3_output,
};

const uint8_t ei_output_tensors_indices_1128090_3[1] = { 0 };
const uint8_t ei_output_tensors_size_1128090_3 = 1;
ei_learning_block_config_tflite_graph_t ei_learning_block_config_1128090_3 = {
    .implementation_version = 1,
    .block_id = 3,
    .output_tensors_indices = ei_output_tensors_indices_1128090_3,
    .output_tensors_size = ei_output_tensors_size_1128090_3,
    .quantized = 1,
    .compiled = 1,
    .graph_config = (void*)&ei_config_graph_1128090_3,
    .dequantize_output = 0,
};

const uint8_t ei_learning_blocks_1128090_1_size = 1;
const uint32_t ei_learning_block_1128090_3_inputs[1] = { 2 };
const uint8_t ei_learning_block_1128090_3_inputs_size = 1;
const ei_learning_block_t ei_learning_blocks_1128090_1[ei_learning_blocks_1128090_1_size] = {
    {
        3,
        &run_nn_inference,
        (void*)&ei_learning_block_config_1128090_3,
        EI_CLASSIFIER_IMAGE_SCALING_NONE,
        ei_learning_block_1128090_3_inputs,
        ei_learning_block_1128090_3_inputs_size,
    },
};

ei_fill_result_classification_i8_config_t ei_fill_result_classification_i8_config_1128090_3 = {
    .zero_point = -128,
    .scale = 0.00390625
};

const size_t ei_postprocessing_blocks_1128090_1_size = 1;
const ei_postprocessing_block_t ei_postprocessing_blocks_1128090_1[ei_postprocessing_blocks_1128090_1_size] = {
    {
        .block_id = 3,
        .type = EI_CLASSIFIER_MODE_CLASSIFICATION,
        .init_fn = NULL,
        .deinit_fn = NULL,
        .postprocess_fn = &process_classification_i8,
        .display_fn = NULL,
        .config = (void*)&ei_fill_result_classification_i8_config_1128090_3,
        .input_block_id = 3
    },
};

const uint8_t freeform_outputs_1128090_1_size = 0;

uint32_t *freeform_outputs_1128090_1 = nullptr;

const ei_impulse_t impulse_1128090_1 = {
    .project_id = 1128090,
    .project_owner = "Norik",
    .project_name = "SolarGuard Edge",
    .impulse_id = 1,
    .impulse_name = "Impulse #1",
    .deploy_version = 1,

    .nn_input_frame_size = 42,
    .raw_sample_count = 110,
    .raw_samples_per_frame = 6,
    .dsp_input_frame_size = 110 * 6,
    .input_width = 0,
    .input_height = 0,
    .input_frames = 0,
    .interval_ms = 90.9090909090909,
    .frequency = 11,

    .dsp_blocks_size = ei_dsp_blocks_1128090_1_size,
    .dsp_blocks = ei_dsp_blocks_1128090_1,

    .learning_blocks_size = ei_learning_blocks_1128090_1_size,
    .learning_blocks = ei_learning_blocks_1128090_1,

    .postprocessing_blocks_size = ei_postprocessing_blocks_1128090_1_size,
    .postprocessing_blocks = ei_postprocessing_blocks_1128090_1,

    .output_tensors_size = 1,

    .inferencing_engine = EI_CLASSIFIER_TFLITE,

    .sensor = EI_CLASSIFIER_SENSOR_FUSION,
    .fusion_string = "voltage + current + power + temperature + ambientTemp + irradiance",
    .slice_size = (110/4),
    .slices_per_model_window = 4,

    .has_anomaly = EI_ANOMALY_TYPE_UNKNOWN,
    .label_count = 4,
    .categories = ei_classifier_inferencing_categories_1128090_1,
    .results_type = EI_CLASSIFIER_TYPE_CLASSIFICATION,
    .freeform_outputs_size = freeform_outputs_1128090_1_size,
    .freeform_outputs = freeform_outputs_1128090_1
};

ei_impulse_handle_t impulse_handle_1128090_1 = ei_impulse_handle_t( &impulse_1128090_1 );

ei_impulse_handle_t& ei_default_impulse = impulse_handle_1128090_1;
constexpr auto& ei_classifier_inferencing_categories = ei_classifier_inferencing_categories_1128090_1;
const auto ei_dsp_blocks_size = ei_dsp_blocks_1128090_1_size;
ei_model_dsp_t *ei_dsp_blocks = ei_dsp_blocks_1128090_1;
#endif // _EI_CLASSIFIER_MODEL_VARIABLES_H_
